FROM node:20-alpine as development

WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm ci

# Copy the rest of the code
COPY . .

# Expose the port the app runs on
EXPOSE 4200

# Command to run the app
CMD ["npm", "start", "--", "--host", "0.0.0.0", "--poll", "500"]