name: LNYQE CI/CD Pipeline

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Test
      run: npm run ci:test

    - name: Build
      run: npm run ci:build

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist
        path: dist/

  build-docker-images:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
    - uses: actions/checkout@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWSACCESSKEYID }}
        aws-secret-access-key: ${{ secrets.AWSSECRETACCESSKEY }}
        aws-region: ${{ secrets.AWSREGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2
      with:
        mask-password: true

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile.prod
        push: true
        tags: |
          ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECRREPOSITORY }}:latest
          ${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECRREPOSITORY }}:${{ github.sha }}

  deploy-to-aws:
    needs: build-docker-images
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'

    steps:
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWSACCESSKEYID }}
        aws-secret-access-key: ${{ secrets.AWSSECRETACCESSKEY }}
        aws-region: ${{ secrets.AWSREGION }}

    # Verify ECS task definition and inspect it for potential issues
    - name: Verify ECS task definition
      id: check-task-def
      run: |
        echo "Retrieving task definition..."
        TASK_DEF_ARN=$(aws ecs describe-services --cluster ${{ secrets.ECSCLUSTER }} --services ${{ secrets.ECSSERVICE }} | jq -r '.services[0].taskDefinition')
        aws ecs describe-task-definition --task-definition $TASK_DEF_ARN > task_def.json
        
        echo "Task definition details:"
        jq '.taskDefinition.containerDefinitions[0].image, .taskDefinition.containerDefinitions[0].essential, .taskDefinition.containerDefinitions[0].portMappings' task_def.json
        
        # Check if there are any required environment variables
        echo "Environment variables:"
        jq '.taskDefinition.containerDefinitions[0].environment' task_def.json
        
        # Check resource limits
        echo "Container resource limits:"
        jq '.taskDefinition.containerDefinitions[0].cpu, .taskDefinition.containerDefinitions[0].memory' task_def.json

    # Check ECS service configuration
    - name: Check ECS service status
      id: check-service
      run: |
        echo "Checking current ECS service status..."
        aws ecs describe-services \
          --cluster ${{ secrets.ECSCLUSTER }} \
          --services ${{ secrets.ECSSERVICE }} > service_status.json
        
        # Check if service is already being deployed
        pending_count=$(jq '.services[0].deployments | length' service_status.json)
        if [ $pending_count -gt 1 ]; then
          echo "::warning::There is already a deployment in progress. Waiting before attempting new deployment."
          sleep 60
        fi
        
        # Check if the service has any events that might indicate issues
        echo "Recent service events:"
        jq -r '.services[0].events[:5][] | .message' service_status.json
        
        # Check if there are any issues with the VPC configuration
        echo "Network configuration:"
        jq '.services[0].networkConfiguration' service_status.json

    # Update ECS service with retries and improved error handling
    - name: Update ECS service
      id: update-service
      run: |
        max_attempts=3
        attempt=1
        backoff_seconds=30
        
        while [ $attempt -le $max_attempts ]; do
          echo "Attempt $attempt of $max_attempts to update ECS service..."
          
          if aws ecs update-service \
            --cluster ${{ secrets.ECSCLUSTER }} \
            --service ${{ secrets.ECSSERVICE }} \
            --network-configuration "awsvpcConfiguration={subnets=['subnet-06f217639afe889bb','subnet-0f56cdbfc696f03a8'],securityGroups=['sg-060182ba59dbd20e1'],assignPublicIp=ENABLED}" \
            --force-new-deployment; then
              echo "ECS service update initiated successfully!"
              break
          else
            exit_code=$?
            echo "Update failed with exit code: $exit_code"
            
            if [ $attempt -lt $max_attempts ]; then
              echo "Waiting ${backoff_seconds} seconds before retry..."
              sleep $backoff_seconds
              backoff_seconds=$(( backoff_seconds * 2 ))
            else
              echo "::error::Failed to update ECS service after $max_attempts attempts."
              exit 1
            fi
          fi
          
          attempt=$((attempt + 1))
        done
 
    # Check for stopped tasks to diagnose the root cause
    - name: Check for stopped tasks
      id: check-stopped-tasks
      run: |
        echo "Checking for recently stopped tasks to diagnose issues..."
        STOPPED_TASKS=$(aws ecs list-tasks \
          --cluster ${{ secrets.ECSCLUSTER }} \
          --family $(aws ecs describe-services --cluster ${{ secrets.ECSCLUSTER }} --services ${{ secrets.ECSSERVICE }} | jq -r '.services[0].taskDefinition' | cut -d'/' -f2 | cut -d':' -f1) \
          --desired-status STOPPED \
          --output json)
        
        TASK_ARNS=$(echo $STOPPED_TASKS | jq -r '.taskArns[]')
        
        if [ -n "$TASK_ARNS" ]; then
          echo "Found stopped tasks. Checking reason for failure..."
          aws ecs describe-tasks \
            --cluster ${{ secrets.ECSCLUSTER }} \
            --tasks $TASK_ARNS > stopped_tasks.json
          
          # Display the task stop reason
          echo "Task stop reasons:"
          jq -r '.tasks[] | .stoppedReason' stopped_tasks.json
          
          # Display container stop reason
          echo "Container stop details:"
          jq -r '.tasks[] | .containers[] | {name: .name, reason: .reason, exitCode: .exitCode}' stopped_tasks.json
          
          # If there are any container insights, get the logs
          for TASK_ARN in $TASK_ARNS; do
            TASK_ID=$(echo $TASK_ARN | cut -d'/' -f2)
            echo "Attempting to get logs for task $TASK_ID..."
            aws logs get-log-events \
              --log-group-name "/ecs/${{ secrets.ECSCLUSTER }}" \
              --log-stream-name "ecs/container-name/$TASK_ID" \
              --limit 20 || echo "No logs available for this task"
          done
        else
          echo "No stopped tasks found."
        fi

    # For deployment status check with improved diagnostics
    - name: Wait for service to stabilize
      id: wait-for-deployment
      timeout-minutes: 15
      run: |
        echo "Waiting for ECS service to stabilize (timeout after 15 minutes)..."
        
        max_checks=30
        check=1
        wait_time=30
        deployment_failed=false
        
        while [ $check -le $max_checks ]; do
          echo "Check $check of $max_checks: Verifying service stability..."
          
          # Get detailed service status
          aws ecs describe-services \
            --cluster ${{ secrets.ECSCLUSTER }} \
            --services ${{ secrets.ECSSERVICE }} > current_status.json
            
          # Check for failed deployments
          deployment_status=$(jq -r '.services[0].deployments[0].status' current_status.json)
          running_count=$(jq -r '.services[0].deployments[0].runningCount' current_status.json)
          desired_count=$(jq -r '.services[0].deployments[0].desiredCount' current_status.json)
          
          echo "Deployment status: $deployment_status, Running: $running_count, Desired: $desired_count"
          
          # Check for any failed tasks
          failed_tasks=$(jq -r '.services[0].failures | length' current_status.json)
          if [ "$failed_tasks" -gt 0 ] || [ "$deployment_status" = "FAILED" ]; then
            echo "::error::Deployment failed. Found $failed_tasks failed tasks."
            jq '.services[0].failures' current_status.json
            deployment_failed=true
            break
          fi
          
          # Check service events for any errors
          echo "Recent events:"
          jq -r '.services[0].events[0:2][] | .message' current_status.json
          
          # Check if deployment is stable
          if [ "$running_count" -eq "$desired_count" ] && [ "$desired_count" -gt 0 ]; then
            # Use the wait command as an additional verification
            if aws ecs wait services-stable \
              --cluster ${{ secrets.ECSCLUSTER }} \
              --services ${{ secrets.ECSSERVICE }}; then
                echo "ECS service has stabilized successfully!"
                echo "Deployment completed successfully!"
                exit 0
            fi
          fi
          
          # If we've checked multiple times and running count is still 0 despite desired > 0,
          # then check for task placement issues
          if [ $check -gt 5 ] && [ "$running_count" -eq 0 ] && [ "$desired_count" -gt 0 ]; then
            echo "Container is failing to start. Checking task placement..."
            TASK_ARNS=$(aws ecs list-tasks \
              --cluster ${{ secrets.ECSCLUSTER }} \
              --service-name ${{ secrets.ECSSERVICE }} \
              --desired-status RUNNING \
              --output json | jq -r '.taskArns[]')
            
            if [ -z "$TASK_ARNS" ]; then
              echo "No running tasks found. Checking for task placement failures..."
              latest_service_event=$(jq -r '.services[0].events[0].message' current_status.json)
              echo "Latest service event: $latest_service_event"
              
              echo "Setting desired count to 0 and then back to 1 to force redeployment..."
              aws ecs update-service \
                --cluster ${{ secrets.ECSCLUSTER }} \
                --service ${{ secrets.ECSSERVICE }} \
                --desired-count 0
              
              echo "Waiting 30 seconds before setting desired count back to 1..."
              sleep 30
              
              aws ecs update-service \
                --cluster ${{ secrets.ECSCLUSTER }} \
                --service ${{ secrets.ECSSERVICE }} \
                --desired-count 1
              
              echo "Reset desired count to 1. Continuing to monitor..."
            fi
          fi
          
          if [ $check -lt $max_checks ]; then
            echo "Waiting ${wait_time} seconds before checking again..."
            sleep $wait_time
          else
            echo "::warning::ECS service did not stabilize within allowed time."
            deployment_failed=true
          fi
          
          check=$((check + 1))
        done
        
        if [ "$deployment_failed" = true ]; then
          echo "::error::Deployment failed to stabilize. Please check ECS console for details."
          
          # As a last attempt, get any CloudWatch logs if available
          echo "Attempting to fetch container logs..."
          aws logs describe-log-groups --log-group-name-prefix "/ecs/${{ secrets.ECSCLUSTER }}" || echo "No log groups found"
          
          exit 1
        fi
